name: 解析器错误
description: Report parser bug
title: "[解析器错误]"
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        描述问题前，请先更新到最新版本。
        最新版本: [version](https://img.shields.io/docker/v/estrellaxd/auto_bangumi)
        本模板仅限于解析器匹配错误。目前 AB 并不能解析类似 `[1-12]` 这样的合集
  - type: input
    id: version
    attributes:
      label: 当前程序版本
      description: 遇到问题时程序所在的版本号
    validations:
      required: true
  - type: dropdown
    id: language
    attributes:
      label: 解析器语言设置
      description: 你是用那种语言碰到了问题
      options:
        - 默认：zh
        - en
        - jp
    validations:
      required: true
  - type: dropdown
    id: TMDB
    attributes:
      label: TMDB 解析
      description: 是否开启 TMDB 解析
      options:
        - 是
        - 否
    validations:
      required: true
  - type: input
    id: RawName
    attributes:
      label: 字幕组提供的名称
    validations:
      required: true
  - type: input
    id: ErrorName
    attributes:
      label: 错误识别名称
      description: 解析错误的名称，如果出现 `Not Matched` 确实非合集之类的无法解析的名称后再提交 issue
    validations:
      required: true