name: 重命名错误
description: Report parser bug
title: "[重命名错误]"
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        描述问题前，请先更新到最新版本。
        最新版本: [version](https://img.shields.io/docker/v/estrellaxd/auto_bangumi)
        本模板仅限于重命名错误。目前 AB 并不能重命名合集，或者以文件夹形式下载的番剧，如果出现类似错误请等待版本更新！
  - type: input
    id: version
    attributes:
      label: 当前程序版本
      description: 遇到问题时程序所在的版本号
    validations:
      required: true
  - type: dropdown
    id: language
    attributes:
      label: 重命名设置
      description: 你是用那重命名设置出现问题
      options:
        - 默认：pn
        - normal
        - advance
    validations:
      required: true
  - type: input
    id: RawName
    attributes:
      label: 种子名称
      description: 原本种子的名称
    validations:
      required: true
  - type: input
    id: path
    attributes:
      label: 文件路径
      description: 种子所在的目录，请以 AB 创建的文件夹为例子，如：`/Lycoris Recoil/Season 1/`，如果没有创建类似的文件夹请参考 [FAQ]() 中的排错指南。
    validations:
      required: true
  - type: input
    id: ErrorName
    attributes:
      label: 错误命名
      description: 重命名错误的名称
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: 发生问题时系统日志
      description: 如果有条件，请打开 Debug 模式复制针对错误命名的日志。
      render: shell